### ISSUE TITLE
[Bug] Archive build

### ISSUE THREAD

**Issue by Schlaubischlump** [trojanfoe/xcodedevtools#4]
If you create an archive build, the environment action is set to 'install' not to build. That means the script is never executed. To fix this you can add an additional `and action != 'install'` to the main function.

**Comment by trojanfoe** [comment]
Hey I've only just seen this issue - sorry about that.  I will fix that shortly - many thanks.

**Comment by trojanfoe** [comment]
Done.  But untested.
