### ISSUE TITLE
No such file or directory: u'@loader_path/../Frameworks/

### ISSUE THREAD

**Issue by ahmed23khan** [trojanfoe/xcodedevtools#6]
Hi,

I have a '.framework' inside my Xcode project(macOS app) which has many dependancies(.dylibs). I was trying to use these scripts to bundle the dependancies of the framework so that I can deploy the App in user's machine.

I have followed the given instruction to configure the scripts inside Xcode.

But, when I run the project on Xcode, I get the following error 'No such file or directory: u'@loader_path/../Frameworks/'

<img width="1146" alt="Screenshot 2022-10-11 at 12 49 04 pm" src="https://user-images.githubusercontent.com/14121480/195082475-d56ee7ad-3d3b-4d51-9bc7-0cd9542b9814.png">

Error Message: 

`Examining SampleMacAppObjc
 ...found @loader_path/../Frameworks/ConnectionCheckerLibrary.framework/Versions/A/ConnectionCheckerLibrary
Traceback (most recent call last):
  File "/Users/thinkcybertk1/Documents/ConnectionChecker_Code/SampleMacAppObjc/External/xcodedevtools/copy_dylibs.py", line 199, in <module>
    exitcode = main(sys.argv)
  File "/Users/thinkcybertk1/Documents/ConnectionChecker_Code/SampleMacAppObjc/External/xcodedevtools/copy_dylibs.py", line 178, in main
    copy_dependencies(executable_file)
  File "/Users/thinkcybertk1/Documents/ConnectionChecker_Code/SampleMacAppObjc/External/xcodedevtools/copy_dylibs.py", line 96, in copy_dependencies
    copy_dylib(dep)
  File "/Users/thinkcybertk1/Documents/ConnectionChecker_Code/SampleMacAppObjc/External/xcodedevtools/copy_dylibs.py", line 61, in copy_dylib
    shutil.copyfile(src, dest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'@loader_path/../Frameworks/ConnectionCheckerLibrary.framework/Versions/A/ConnectionCheckerLibrary'

Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by trojanfoe** [comment]
OK so I have attempted a fix but as I haven't done any dev on macOS for so long I have no way to test it.  Therefore I have put the fix into the `fixes/at_sign` branch. Please check that branch out and let me know if this does the trick and then I'll merge it into `master`.

**Comment by ahmed23khan** [comment]
Hi @trojanfoe ,

I tried the new changes. It builds, but it crashes when I run.

**Error Message:**
`dyld[46751]: Library not loaded: @rpath/ConnectionCheckerLibrary
  Referenced from: /Users/thinkcybertk1/Library/Developer/Xcode/DerivedData/SampleMacAppObjc-cfcfhayzstdjzcewypvmydnjwlct/Build/Products/Debug/SampleMacAppObjc.app/Contents/MacOS/SampleMacAppObjc
  Reason: tried: '/Users/thinkcybertk1/Library/Developer/Xcode/DerivedData/SampleMacAppObjc-cfcfhayzstdjzcewypvmydnjwlct/Build/Products/Debug/ConnectionCheckerLibrary' (no such file), '/usr/lib/system/introspection/ConnectionCheckerLibrary' (no such file), '/Users/thinkcybertk1/Library/Developer/Xcode/DerivedData/SampleMacAppObjc-cfcfhayzstdjzcewypvmydnjwlct/Build/Products/Debug/SampleMacAppObjc.app/Contents/MacOS/../Frameworks/ConnectionCheckerLibrary' (no such file), '/Users/thinkcybertk1/Library/Developer/Xcode/DerivedData/SampleMacAppObjc-cfcfhayzstdjzcewypvmydnjwlct/Build/Products/Debug/SampleMacAppObjc.app/Contents/MacOS/../Frameworks/ConnectionCheckerLibrary' (no such file), '/usr/local/lib/ConnectionCheckerLibrary' (no such file), '/usr/lib/ConnectionCheckerLibrary' (no such file)`

I guess the script is not looking for the 'ConnectionCheckerLibrary.framework' in the right place.


<img width="704" alt="Screenshot 2022-10-12 at 1 03 52 pm" src="https://user-images.githubusercontent.com/14121480/195337297-d1962ef3-924f-4194-b6ed-a8c5fff82f64.png">

**Comment by andyduplain** [comment]
Thanks for the update. I need to know more about your project.  It looks to me like you build a framework from source and then embed that into an app bundle.  I wonder if it would be possible to make `copy_dylibs.py` work in *framework mode* as well as the normal *app mode*...

**Comment by ahmed23khan** [comment]
Hi @andyduplain ,

Yes the objective - C' .framework' is built using the [https://github.com/mono/Embeddinator-4000](url) 

and later added on the sample app(macOS).

Basically, the [https://github.com/mono/Embeddinator-4000](url)  uses [https://github.com/mono/mono](url) to port the C#  DLLs into a Objective - C '.Framework'

**Comment by andyduplain** [comment]
It's fairly clear then that the issue is in the building of the `.framework` and there isn't much that can be done about it after the fact.

You see if the `.dylib`s are not embedded into the  `.framework` bundle at the time of building they cannot be accessed by the *user* of the `.framework`, unless the framework is on the same system as the app.

It does not make sense to change `copy_dylibs.py` to fix that kind of issue, however, as mentioned above, it might make sense for a modified version of `copy_dylibs.py` to be used to help build the framework.

Please contact the people that run the Embeddinator project and tell them that they are generating invalid `.framework` bundles.

**Comment by ahmed23khan** [comment]
@trojanfoe In my case, the ```.dylibs```  which are referenced in the ```.framework``` are in my system  at ```/Library/Frameworks//Versions/6.12.0/lib/libmonosgen-2.0.1.dylib``` 

I wanted to bundle this dependency ```.dylib``` in my app bundle so that the user does not have to install the entire ```Mono.framework```

**Comment by trojanfoe** [comment]
@ahmed23khan that’s an unusual workflow and will never be supported by `copy_dylibs.py`. You need to talk to whoever built the framework.
